spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:warsztat
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show_sql: true
    hibernate.ddl-auto: create-drop
    hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.hbm2ddl.auto: update
    hibernate.id.new_generator_mappings: true

  h2:
    console:
      enabled: true
      path: /h2-console